# Generated by Django 2.2.3 on 2019-08-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile1',
            old_name='agreement',
            new_name='agreement1',
        ),
        migrations.AddField(
            model_name='profile1',
            name='agreement2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile1',
            name='agreement3',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
