# Generated by Django 2.2.3 on 2019-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_app', '0003_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='Bookperm',
            field=models.BooleanField(default=0),
        ),
    ]
