# Generated by Django 2.2.3 on 2019-08-08 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ms_app', '0004_library_bookperm'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='pub_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
