# Generated by Django 2.2.3 on 2019-08-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0004_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
