# Generated by Django 2.2.3 on 2019-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0006_profile2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile2',
            name='evidence',
        ),
        migrations.AddField(
            model_name='profile2',
            name='test_record',
            field=models.FileField(blank=True, upload_to='musics/'),
        ),
    ]
