# Generated by Django 2.2.3 on 2019-08-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_app', '0003_library'),
        ('vr_app', '0007_auto_20190806_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('m_1365_id', models.CharField(max_length=30)),
                ('privacy', models.CharField(max_length=150)),
                ('primarykey', models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ms_app.Library')),
            ],
        ),
    ]
