# Generated by Django 2.2.3 on 2019-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0008_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile2',
            name='mileage',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
