# Generated by Django 2.2.3 on 2019-08-08 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0010_apply_bookpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='m_1365_id',
            new_name='vms_1365_id',
        ),
        migrations.AddField(
            model_name='apply',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='writer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
