# Generated by Django 2.2.3 on 2019-08-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0011_auto_20190809_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='BookPermission',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='date',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='vms_1365_id',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='writer_name',
        ),
        migrations.AddField(
            model_name='apply',
            name='author',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='apply',
            name='book_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='apply',
            name='publisher',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='apply',
            name='real_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='apply',
            name='username',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='apply',
            name='vms_or_1365',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='apply',
            name='vr_accounts',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='apply',
            name='sms',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
