# Generated by Django 2.2.3 on 2019-08-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0012_auto_20190809_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='author',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='real_name',
        ),
    ]
