# Generated by Django 2.2.3 on 2019-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0014_auto_20190809_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile2',
            name='realmile',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
