# Generated by Django 2.2.3 on 2019-08-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0015_profile2_realmile'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdata',
            name='question_visit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='birth_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_contents', models.CharField(max_length=200)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vr_app.HelpData')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
