# Generated by Django 2.2.3 on 2019-08-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0016_auto_20190809_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='sms',
        ),
    ]
