# Generated by Django 2.2.3 on 2019-08-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0018_apply_vr_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='vr_time',
        ),
    ]
